export const actionType = {
  // FOR SIGNUP
  REQUEST_SIGNUP: "REQUEST_SIGNUP",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",

  // FOR SIGNIN
  REQUEST_SIGNIN: "REQUEST_SIGNIN",
  SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
  SIGNIN_FAILURE: "SIGNIN_FAILURE",

  // FOR LOGOUT
  REQUEST_LOGOUT: "REQUEST_LOGOUT",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",


};
